name: flutter_app_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  path: ^1.9.0
  path_provider: ^2.1.4
  image: ^4.3.0
  flutter_firebase_chat_core: ^1.6.8
  voice_message_package: ^2.2.1
  sizer: ^3.0.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  sqflite: ^2.4.0
  record: ^5.1.2
  just_audio: ^0.9.41
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
